### ISSUE TITLE
[Question] Are there any plans to add a formatter feature?

### ISSUE THREAD

**Issue by yaegassy** [pappasam/nginx-language-server#9]
I thought it would be useful to add a formatter feature to `nginx-language-server`.

As you may know, there is a python tool called `nginxfmt`.

- <https://github.com/slomkowski/nginx-config-formatter>

How about the idea of running this command from the language server?

Of course, you can use `diagnostic-language-server` (`coc-diagnostic`) to configure it, but many people may find it useful to have the features integrated in the language server itself.

**Comment by pappasam** [comment]
@yaegassy good question! It's not on my short-term roadmap because I personally use my own plugin for formatting files: https://github.com/pappasam/vim-filetype-formatter

I support https://github.com/vasilevich/nginxbeautifier out of the box there. Happy to consider adding a formatter though because it's definitely in-scope for the project!

**Comment by pappasam** [comment]
Just tried nginx-config-formatter. Nice tool, I'd be fine adding that as a dependency and supporting code formatting with this language server.

**Comment by yaegassy** [comment]
I just wanted to share an idea with you, so this issue is closed.

Thanks reply! 🙇
